//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSite.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual task remaining.
        /// </summary>
        public static string ACTUAL_BD {
            get {
                return ResourceManager.GetString("ACTUAL_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agile Board.
        /// </summary>
        public static string AgileBoard {
            get {
                return ResourceManager.GetString("AgileBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Team.
        /// </summary>
        public static string AssignTeam {
            get {
                return ResourceManager.GetString("AssignTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project&apos;s backlog.
        /// </summary>
        public static string Backlog {
            get {
                return ResourceManager.GetString("Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ChangingPassword {
            get {
                return ResourceManager.GetString("ChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CloseAllSprint {
            get {
                return ResourceManager.GetString("CloseAllSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments not found.
        /// </summary>
        public static string CommentsNot {
            get {
                return ResourceManager.GetString("CommentsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentsTitle {
            get {
                return ResourceManager.GetString("CommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count issues.
        /// </summary>
        public static string CountIssues {
            get {
                return ResourceManager.GetString("CountIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total issues.
        /// </summary>
        public static string CountMainIssues {
            get {
                return ResourceManager.GetString("CountMainIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count sprints.
        /// </summary>
        public static string CountSprints {
            get {
                return ResourceManager.GetString("CountSprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Story.
        /// </summary>
        public static string CountStory {
            get {
                return ResourceManager.GetString("CountStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create issue.
        /// </summary>
        public static string CreateIssueBtn {
            get {
                return ResourceManager.GetString("CreateIssueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new issue in sprint.
        /// </summary>
        public static string CreateNewIssueInSprint {
            get {
                return ResourceManager.GetString("CreateNewIssueInSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string CreateNewProject {
            get {
                return ResourceManager.GetString("CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new sprint.
        /// </summary>
        public static string CreateNewSprint {
            get {
                return ResourceManager.GetString("CreateNewSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sprint.
        /// </summary>
        public static string CreateSprint {
            get {
                return ResourceManager.GetString("CreateSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create team.
        /// </summary>
        public static string CreateTeam {
            get {
                return ResourceManager.GetString("CreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create team.
        /// </summary>
        public static string CreateTeamInfo {
            get {
                return ResourceManager.GetString("CreateTeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string DateBegin {
            get {
                return ResourceManager.GetString("DateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform this action?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete project?.
        /// </summary>
        public static string DeleteProjectQuestion {
            get {
                return ResourceManager.GetString("DeleteProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete sprint?.
        /// </summary>
        public static string DeleteSprintQuestion {
            get {
                return ResourceManager.GetString("DeleteSprintQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing project.
        /// </summary>
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing sprint.
        /// </summary>
        public static string EditSprint {
            get {
                return ResourceManager.GetString("EditSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sprint.
        /// </summary>
        public static string EditSprintTitle {
            get {
                return ResourceManager.GetString("EditSprintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit team.
        /// </summary>
        public static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint cannot be closed because contains not fixed issues..
        /// </summary>
        public static string ErrorCloseSprint {
            get {
                return ResourceManager.GetString("ErrorCloseSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ErrorComparePassword {
            get {
                return ResourceManager.GetString("ErrorComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project cannot be saved without a team.
        /// </summary>
        public static string ErrorCreatePtojectTeamId {
            get {
                return ResourceManager.GetString("ErrorCreatePtojectTeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can&apos;t be deleted..
        /// </summary>
        public static string ErrorDeleteUser {
            get {
                return ResourceManager.GetString("ErrorDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ErrorLengthPassword {
            get {
                return ResourceManager.GetString("ErrorLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string ErrorProfile {
            get {
                return ResourceManager.GetString("ErrorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project has already contained active sprint!.
        /// </summary>
        public static string ErrorStartSprint {
            get {
                return ResourceManager.GetString("ErrorStartSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists or has the contract.
        /// </summary>
        public static string ErrorUserExist {
            get {
                return ResourceManager.GetString("ErrorUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal burndown remaining.
        /// </summary>
        public static string IDEAL_DB {
            get {
                return ResourceManager.GetString("IDEAL_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to invite user!.
        /// </summary>
        public static string InviteError {
            get {
                return ResourceManager.GetString("InviteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite has been sent..
        /// </summary>
        public static string InviteSentInform {
            get {
                return ResourceManager.GetString("InviteSentInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create issue.
        /// </summary>
        public static string IssueAdd {
            get {
                return ResourceManager.GetString("IssueAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignee.
        /// </summary>
        public static string IssueAsignee {
            get {
                return ResourceManager.GetString("IssueAsignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string IssueChild {
            get {
                return ResourceManager.GetString("IssueChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string IssueChildren {
            get {
                return ResourceManager.GetString("IssueChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string IssueComments {
            get {
                return ResourceManager.GetString("IssueComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        public static string IssueEstimate {
            get {
                return ResourceManager.GetString("IssueEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All issues.
        /// </summary>
        public static string IssueFilterAll {
            get {
                return ResourceManager.GetString("IssueFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string IssueFilterFixed {
            get {
                return ResourceManager.GetString("IssueFilterFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string IssueFilterInProgress {
            get {
                return ResourceManager.GetString("IssueFilterInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My issues.
        /// </summary>
        public static string IssueFilterMy {
            get {
                return ResourceManager.GetString("IssueFilterMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open issues.
        /// </summary>
        public static string IssueFilterOpen {
            get {
                return ResourceManager.GetString("IssueFilterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string IssueFilterVerified {
            get {
                return ResourceManager.GetString("IssueFilterVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue info.
        /// </summary>
        public static string IssueInfo {
            get {
                return ResourceManager.GetString("IssueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string IssueParent {
            get {
                return ResourceManager.GetString("IssueParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string IssuePriority {
            get {
                return ResourceManager.GetString("IssuePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string IssueProject {
            get {
                return ResourceManager.GetString("IssueProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issues.
        /// </summary>
        public static string Issues_small {
            get {
                return ResourceManager.GetString("Issues_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent.
        /// </summary>
        public static string IssueSpentTime {
            get {
                return ResourceManager.GetString("IssueSpentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        public static string IssueSprint {
            get {
                return ResourceManager.GetString("IssueSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string IssueState {
            get {
                return ResourceManager.GetString("IssueState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string IssueStateInProgress {
            get {
                return ResourceManager.GetString("IssueStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string IssueStateOpen {
            get {
                return ResourceManager.GetString("IssueStateOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string IssueType {
            get {
                return ResourceManager.GetString("IssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you don&apos;t have any active projects yet....
        /// </summary>
        public static string NO_PROJECTS_YET {
            get {
                return ResourceManager.GetString("NO_PROJECTS_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available projects.
        /// </summary>
        public static string NoAvailableProjects {
            get {
                return ResourceManager.GetString("NoAvailableProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No avalible projects.
        /// </summary>
        public static string NoProjects {
            get {
                return ResourceManager.GetString("NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sprints in this project.
        /// </summary>
        public static string NoSprintsInThisProject {
            get {
                return ResourceManager.GetString("NoSprintsInThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stories in this sprint.
        /// </summary>
        public static string NoStoriesInThisSprint {
            get {
                return ResourceManager.GetString("NoStoriesInThisSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not confirmed.
        /// </summary>
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Due.
        /// </summary>
        public static string PastDue {
            get {
                return ResourceManager.GetString("PastDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        public static string Planning {
            get {
                return ResourceManager.GetString("Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ProfileH4 {
            get {
                return ResourceManager.GetString("ProfileH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects no found.
        /// </summary>
        public static string ProjectsNoFound {
            get {
                return ResourceManager.GetString("ProjectsNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove sprint.
        /// </summary>
        public static string RemoveSprint {
            get {
                return ResourceManager.GetString("RemoveSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopened.
        /// </summary>
        public static string Reopened {
            get {
                return ResourceManager.GetString("Reopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search teams request.
        /// </summary>
        public static string SearchTeams {
            get {
                return ResourceManager.GetString("SearchTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search users request.
        /// </summary>
        public static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invite.
        /// </summary>
        public static string SendInvite {
            get {
                return ResourceManager.GetString("SendInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input email for invite user:.
        /// </summary>
        public static string SendInviteInfo {
            get {
                return ResourceManager.GetString("SendInviteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invite.
        /// </summary>
        public static string SendInviteTitle {
            get {
                return ResourceManager.GetString("SendInviteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint&apos;s backlog.
        /// </summary>
        public static string Sprint {
            get {
                return ResourceManager.GetString("Sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sprint details.
        /// </summary>
        public static string SPRINT_DETAILS {
            get {
                return ResourceManager.GetString("SPRINT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint is stoped.
        /// </summary>
        public static string SprintIsClosed {
            get {
                return ResourceManager.GetString("SprintIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint is started.
        /// </summary>
        public static string SprintIsStarted {
            get {
                return ResourceManager.GetString("SprintIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprints.
        /// </summary>
        public static string Sprints {
            get {
                return ResourceManager.GetString("Sprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Project.
        /// </summary>
        public static string StateProject {
            get {
                return ResourceManager.GetString("StateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string TaskFixed {
            get {
                return ResourceManager.GetString("TaskFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string TaskInProgress {
            get {
                return ResourceManager.GetString("TaskInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TaskOpen {
            get {
                return ResourceManager.GetString("TaskOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be between  3 and 9 characters.
        /// </summary>
        public static string TeamValidationLength {
            get {
                return ResourceManager.GetString("TeamValidationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message here....
        /// </summary>
        public static string TextComments {
            get {
                return ResourceManager.GetString("TextComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time tracking.
        /// </summary>
        public static string TimeTracking {
            get {
                return ResourceManager.GetString("TimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string TimeTrackingComment {
            get {
                return ResourceManager.GetString("TimeTrackingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file type.
        /// </summary>
        public static string UnsupportedFile {
            get {
                return ResourceManager.GetString("UnsupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated..
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the correct date! Maybe sprint already exist with the such values date..
        /// </summary>
        public static string ValidationCheckDate {
            get {
                return ResourceManager.GetString("ValidationCheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the correct date! Maybe sprint already exist with the such values date..
        /// </summary>
        public static string ValidationDateInSprint {
            get {
                return ResourceManager.GetString("ValidationDateInSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required field.
        /// </summary>
        public static string ValidationDateRequired {
            get {
                return ResourceManager.GetString("ValidationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key length must be min 2 characters.
        /// </summary>
        public static string ValidationKeyLength {
            get {
                return ResourceManager.GetString("ValidationKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is required field.
        /// </summary>
        public static string ValidationKeyRequired {
            get {
                return ResourceManager.GetString("ValidationKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already exists..
        /// </summary>
        public static string ValidationNameExists {
            get {
                return ResourceManager.GetString("ValidationNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length must be min 6 characters.
        /// </summary>
        public static string ValidationNameLength {
            get {
                return ResourceManager.GetString("ValidationNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required field.
        /// </summary>
        public static string ValidationNameRequired {
            get {
                return ResourceManager.GetString("ValidationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string WarningDelete {
            get {
                return ResourceManager.GetString("WarningDelete", resourceCulture);
            }
        }
    }
}
